/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ModuleRouteImport } from './routes/module'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStoreRouteImport } from './routes/app.store'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPathsRouteImport } from './routes/app.paths'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppPathsPinjolRouteImport } from './routes/app.paths.pinjol'
import { Route as AppPathsPenipuanRouteImport } from './routes/app.paths.penipuan'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleRoute = ModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsPinjolRoute = AppPathsPinjolRouteImport.update({
  id: '/pinjol',
  path: '/pinjol',
  getParentRoute: () => AppPathsRoute,
} as any)
const AppPathsPenipuanRoute = AppPathsPenipuanRouteImport.update({
  id: '/penipuan',
  path: '/penipuan',
  getParentRoute: () => AppPathsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/module': typeof ModuleRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/store': typeof AppStoreRoute
  '/app/paths/penipuan': typeof AppPathsPenipuanRoute
  '/app/paths/pinjol': typeof AppPathsPinjolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/module': typeof ModuleRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/store': typeof AppStoreRoute
  '/app/paths/penipuan': typeof AppPathsPenipuanRoute
  '/app/paths/pinjol': typeof AppPathsPinjolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/module': typeof ModuleRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/store': typeof AppStoreRoute
  '/app/paths/penipuan': typeof AppPathsPenipuanRoute
  '/app/paths/pinjol': typeof AppPathsPinjolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/home'
    | '/login'
    | '/module'
    | '/quiz'
    | '/signup'
    | '/app/leaderboard'
    | '/app/paths'
    | '/app/profile'
    | '/app/store'
    | '/app/paths/penipuan'
    | '/app/paths/pinjol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/home'
    | '/login'
    | '/module'
    | '/quiz'
    | '/signup'
    | '/app/leaderboard'
    | '/app/paths'
    | '/app/profile'
    | '/app/store'
    | '/app/paths/penipuan'
    | '/app/paths/pinjol'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/home'
    | '/login'
    | '/module'
    | '/quiz'
    | '/signup'
    | '/app/leaderboard'
    | '/app/paths'
    | '/app/profile'
    | '/app/store'
    | '/app/paths/penipuan'
    | '/app/paths/pinjol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ModuleRoute: typeof ModuleRoute
  QuizRoute: typeof QuizRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module': {
      id: '/module'
      path: '/module'
      fullPath: '/module'
      preLoaderRoute: typeof ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths': {
      id: '/app/paths'
      path: '/paths'
      fullPath: '/app/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths/pinjol': {
      id: '/app/paths/pinjol'
      path: '/pinjol'
      fullPath: '/app/paths/pinjol'
      preLoaderRoute: typeof AppPathsPinjolRouteImport
      parentRoute: typeof AppPathsRoute
    }
    '/app/paths/penipuan': {
      id: '/app/paths/penipuan'
      path: '/penipuan'
      fullPath: '/app/paths/penipuan'
      preLoaderRoute: typeof AppPathsPenipuanRouteImport
      parentRoute: typeof AppPathsRoute
    }
  }
}

interface AppPathsRouteChildren {
  AppPathsPenipuanRoute: typeof AppPathsPenipuanRoute
  AppPathsPinjolRoute: typeof AppPathsPinjolRoute
}

const AppPathsRouteChildren: AppPathsRouteChildren = {
  AppPathsPenipuanRoute: AppPathsPenipuanRoute,
  AppPathsPinjolRoute: AppPathsPinjolRoute,
}

const AppPathsRouteWithChildren = AppPathsRoute._addFileChildren(
  AppPathsRouteChildren,
)

interface AppRouteChildren {
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPathsRoute: typeof AppPathsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppStoreRoute: typeof AppStoreRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPathsRoute: AppPathsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppStoreRoute: AppStoreRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ModuleRoute: ModuleRoute,
  QuizRoute: QuizRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
